name: CI tests

on:
  push:
    branches: [ main, CI/CD ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (optional)
        run: sudo apt-get install libgl1-mesa-dev -y

      - name: Create build directory
        run: mkdir Saint-Nec-Engine/build

      - name: Build libraries
        run: cmake .. && make -j$(nproc)
        working-directory: ./Saint-Nec-Engine/build/Saint-Nec-Engine-Lib/src

      - name: Build tests
        run: cmake .. && make -j$(nproc)
        working-directory: ./Saint-Nec-Engine/build/Saint-Nec-Engine-Test

      - name: Run tests
        run: |
          ./Saint-Nec-Engine/build/Saint-Nec-Engine-Test/testBoxCollider
          ./Saint-Nec-Engine/build/Saint-Nec-Engine-Test/testCollision
