name: CI tests

on:
  push:
    branches: [ main, CI/CD ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (optional)
        run: sudo apt-get install libgl1-mesa-dev -y

      - name: Create build directory
        run: mkdir -p build

      - name: Configure libraries
        run: cmake ../../Saint-Nec-Engine-Lib
        working-directory: ./build

      - name: Build libraries
        run: make -j$(nproc)
        working-directory: ./build

      - name: Configure tests
        run: cmake ../../Saint-Nec-Engine-Test
        working-directory: ./build

      - name: Build tests
        run: make -j$(nproc)
        working-directory: ./build

      - name: Run tests
        run: |
          ./build/Saint-Nec-Engine-Test/testBoxCollider
          ./build/Saint-Nec-Engine-Test/testCollision
